### ISSUE TITLE
Network Resiliency - Caching

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism.Plugin.Logging#1]
All of the Logging Implementations should be network resilient

- Store logs locally if there is no network connection
- Include a mechanism to send all unsent logs
- Include a mechanism to send oldest log information first before trying new log.

**Comment by RadoslawKubas** [comment]
I did some major refactoring, also in class structure, to retrieve result of post operations and later implement logs local storage and resending in CommonLoger. I committed current version to my fork. What do you think about it? Is this ok for future PR, or dead end? :)

**Comment by dansiegel** [comment]
Send over a PR

**Comment by RadoslawKubas** [comment]
Done, but please remember this version is just to show direction, and discuss changes :) 

BTW, do you have already any idea where store unsent logs, I was thinking about serialising list to   Json or Xml and store in Application.Current.Properties.
