### ISSUE TITLE
Logs not appear in Loggly

### ISSUE THREAD

**Issue by RadoslawKubas** [dansiegel/Prism.Plugin.Logging#2]
First of all all thank you for great job with Prism! 

I'm trying to use Logging plugin to send logs to Loggly free account, everything seems to works fine, no errors, except that logs not appear in my loggly account. I make tests with sample/LoggingDemo and same result. I can send logs to syslog server without any problem, but not to Loggly.

It seems to be everything ok with account and setup I'm using, at lease when I try to send logs to my longgly from mac console, it works fine, logs appear, but not with plugin. 

Do you have any idea, what may be wrong with my setup, or where to look for reason?

Thank you in advance for any help!

**Comment by dansiegel** [comment]
Loggly has two supported methods for sending logs... one is Syslog, the other uses their Restful API. From what I've seen of Loggly it was more reliable to use the API than Syslog. I typically use Syslog for logging to my desktop with VisualSyslog.

Can you clarify what method you're trying when logging to Loggly?

**Comment by RadoslawKubas** [comment]
Thank you for your answer. I'm trying to use API (LogglyHttpLogger). 

When I send logs from command line (with real correct token)

> curl -L https://www.loggly.com/install/LogglySample.log | curl -X POST -H "content-type:text/plain" --data-binary @- http://logs-01.loggly.com/bulk/12345678-1234-1234-1234-1234567890ab/tag/sample

logs appear, but when using same token in  LoggingDemo (or my app), nothing happened. 

I noticed one thing. When logs are sending from the plugin, in some point there is Json message

> HostName = "DESKTOP-9IAV7U0", Priority = None, Category = Debug, Message = "test"

posted to url (again with real correct token)

> https://logs-01.loggly.com/12345678-1234-1234-1234-1234567890ab/tag/LoggingDemo,http,test/

but when I open this address in Safari, blank page with "Invalid API key" message appear.

I'm not sure if this is expected behaviour, or maybe some error.

**Comment by RadoslawKubas** [comment]
I think I found the reason

```
protected Task<HttpResponseMessage> PostMessageAsync(object message, Uri requestUri)
        {
            using(var client = new HttpClient())
            {
                return client.PostAsync(requestUri, new JsonContent(message));
            }
        }
```

It seems, it destroys client before task finish (and result is TaskCanceledException). I checked what happened if await result here and everything works, logs appear in Loggly.

**Comment by RadoslawKubas** [comment]
Ah and one small change more, it needs little different loggly address, like this works fine:

> protected const string LogglyUriTemplate = "{0}/inputs/{1}/tag/{2}/";

**Comment by dansiegel** [comment]
@RadekES I'd be happy to accept a PR ;)

**Comment by RadoslawKubas** [comment]
@dansiegel Done :)
